### ISSUE TITLE
TypeError: unsupported operand type(s) for //: 'int' and 'tuple'

### ISSUE THREAD

**Issue by tralala87** [camenduru/stable-diffusion-diffusers-colab#1]
After running [flax_stable_diffusion_2.ipynb](https://github.com/camenduru/stable-diffusion-diffusers-colab/blob/main/flax_stable_diffusion_2.ipynb)

I get

`TypeError: unsupported operand type(s) for //: 'int' and 'tuple'`

**Comment by upright2003** [comment]
I also have the same problem, can I change it to gradio webui to run?

**Comment by camenduru** [comment]
thanks for the issue ❤ please try again maybe works
